time = input("Please add time: ")
items = input("Please add items: ")
name = input("Please add name: ")
screem = input("please add scream: ")
action = input("please add something to do: ")
parse = "It was %s o'clock when I hears a knock at the door.\nI opened the door and there was a box full of %s with a note saying \"From Mr. %s\".\nJust as I closed the door I heard a scream \"%s\".\nI froze in place and all I could do was %s." % (time, items, name.title(), screem.upper(), action)
print(parse) 